### ISSUE TITLE
Data type in sorting.h

### ISSUE THREAD

**Issue by srirajshukla** [Code-Pickle/c-algos#7]
In **sorting.h** , there is only support for int type. 

What if a float, or string type is passed to the function. It may break down. There needs to be a check to prevent that. And other functions to handle other data types appropriately(?).

**Comment by utk-dev** [comment]
I can think of two ways to go about implementing a sorting algorithm that does not care about the data type of the array in C:
- Use the (void *) pointer type instead of int, float etc. to make it truly type independent and sort the pointers not the actual elements. 
    - Pros: This saves time if the user passes an array of struct pointers where the structs themselves are big.
    - Cons: We need to specify that the user needs to pass an array of pointers; user will also have to specify the comparison function.
- Use a Union with only certain allowed data types. This makes the code quite a bit simpler to comprehend compared to the former method.
    - Pros: We can make sure that it will work will all the data types that we have specified in the Union - much closer to what you want. User will always pass an array of the custom union that we made for him/her/
    - Cons: While unions can store data of multiple types, they don't contain the type information with them. We need a way to pass the data-type that's stored in the union that the user sent us.  

But considering how the code is written in the .cpp files, I'm not sure that either of the methods given above are better than the other.
